/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.labengsw;
import javax.swing.ImageIcon;
import java.awt.Image;
/**
 *
 * @author Arthur
 */
public class InterfaceImage extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(InterfaceImage.class.getName());

    /**
     * Creates new form InterfaceImage
     * @param icon
     */
    private Image originalImg;
    
    public InterfaceImage() {
        initComponents();
        
        this.addComponentListener(new java.awt.event.ComponentAdapter() {
           @Override
           public void componentResized(java.awt.event.ComponentEvent e) {
                Image scaledImg = originalImg.getScaledInstance(
                    lblImage.getWidth(),
                    lblImage.getHeight(), 
                    Image.SCALE_SMOOTH
                );
                lblImage.setIcon(new ImageIcon(scaledImg));
           }
        });
    }
    
    public void setImageIcon(String path) {
        this.originalImg = new ImageIcon(path).getImage();
        lblImage.setIcon(new ImageIcon(originalImg));
        pack();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblImage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(0, 0));
        getContentPane().add(lblImage, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
 
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblImage;
    // End of variables declaration//GEN-END:variables
}
